package main

import (
	"flag"
	"log"
	"os"
	"strings"
	"time"

	"github.com/hysios/nginxcert/internal/certificate"
	"github.com/hysios/nginxcert/internal/nginx"
	"github.com/hysios/nginxcert/internal/updater"
)

func main() {
	author := flag.String("author", "", "Author of the certificates")
	defaultSSLPath := flag.String("ssl-path", "", "Default SSL path")
	config := flag.String("config-path", "", "Nginx config path")
	validity := flag.Int("validity", 90, "Validity period of the certificates")
	domainFilter := flag.String("domain-filter", "", "Comma-separated list of domains to process (empty for all)")
	flag.Parse()

	configDir := *config
	if configDir == "" || *defaultSSLPath == "" || *author == "" {
		flag.Usage()
		os.Exit(1)
	}

	// 解析域名过滤器
	var allowedDomains map[string]bool
	if *domainFilter != "" {
		allowedDomains = make(map[string]bool)
		for _, domain := range strings.Split(*domainFilter, ",") {
			allowedDomains[strings.TrimSpace(domain)] = true
		}
	}

	// 解析Nginx配置
	domains, err := nginx.ParseConfigs(configDir)
	if err != nil {
		log.Fatalf("Failed to parse Nginx configs: %v", err)
	}

	user := &certificate.MyUser{
		Email: *author,
	}

	// 为每个域名生成证书
	for _, domain := range domains {
		// 应用域名过滤器
		if allowedDomains != nil && !allowedDomains[domain.Name] {
			log.Printf("Skipping domain %s (not in filter)", domain.Name)
			continue
		}

		if !domain.SignTime.IsZero() && time.Since(domain.SignTime) < time.Duration(*validity-3)*24*time.Hour {
			log.Printf("Certificate for %s already exists and is valid for another %d days", domain.Name, *validity-3)
			continue
		}

		_, _, err := certificate.GenerateCertificate(user, *defaultSSLPath, &domain)
		if err != nil {
			log.Printf("Failed to generate certificate for %s: %v", domain.Name, err)
			continue
		}

		if domain.ConfigPath == "" {
			continue
		}

		// 更新Nginx配置
		err = updater.UpdateCertificatePaths(domain)
		if err != nil {
			log.Printf("Failed to update config for %s: %v", domain.Name, err)
		}
	}

	log.Printf("Certificates generated by: %s", *author)
	log.Println("Certificate renewal process completed")
}
